### ISSUE TITLE
Entry blocks

### ISSUE THREAD

**Issue by juanshishido** [juanshishido/auto-newsletter#1]
Find the HTML structure such that each entry--i.e., workshop--can be examined individually. Do this so that all relevant information stays together.

Currently, we find all the individual pieces. E.g., all workshop dates. This works if no data is missing, but can be problematic otherwise.

**Comment by juanshishido** [comment]
Something that can help is right clicking on the actual page and selecting "Inspect Element." This can show you the structure better than looking at the HTML can. It also highlights the sections on the page that each block of code corresponds to.

**Comment by trinetta** [comment]
ah ok that's a good tip, thanks Juan!

**Comment by juanshishido** [comment]
There is a div with class "view-content" that has each workshop entry. There are two of these divs, though. Select the second one.

From there, the first entry is in the div with class: "views-row views-row-1 views-row-odd views-row-first"

The second is "views-row views-row-2 views-row-even"

The third is "views-row views-row-3 views-row-odd"

It might be helpful if you can, within the "view-content" div, select all divs that start with "views-row"

Not sure if possible, by @trinetta, @tonyshenyy, and @yadelab should find out.

**Comment by yadelab** [comment]
Hey Juan,

Will you be in the office tomorrow? because I think it would be great if we
can chat about this project. I think we will all benefit if we can all be
on the same page in terms of our contribution to the project. I will be
working form 1-3pm tomorrow so we can discuss then. Let me know.

Sincerely,
Yadel

**Comment by trinetta** [comment]
Yadel, if Juan's not available I can give you a short run down on what the
project is about like what I did with Yiyang last week

**Comment by trinetta** [comment]
hi juan! how do we print something? 

We are trying to test this out: pull out the 'waiting list' or 'register' component

def status(content):
    """ This returns the registration status, whether it's 'waiting list'(full) or 'register'(has vacancies)"""
    return content.find_all('a', class_ = 'register-link')

**Comment by trinetta** [comment]
oh ok we got it to print! but how do we isolate just the 'waiting list' or 'register' word, because now it pulls out the entire line with the url

we are currently on the 16 March 2015 branch!

**Comment by yadelab** [comment]
Can't we parse thru each word in every line of url?

**Comment by juanshishido** [comment]
Your status function will return a list of all of the register-links on the page. When you iterate through each of them, you can use the .text method. For example:

```
# List of register-links
regs = status(content)

# Print the results
for item in regs:
    print item.text
```

Hope this helps!

[Edited for clarity.]

**Comment by juanshishido** [comment]
@yadelab: sorry for not responding earlier. I was not on campus today.

**Comment by juanshishido** [comment]
Of course, related to the code shown above, you don't want to print the results. Rather, you want to store them somewhere or write them to a file.

**Comment by trinetta** [comment]
Hi all, based on the new format of the newsletter, here is what we would now need to export to a csv file

Title (with url link)
Date
Time

For example: 
Reference Management with Zotero (with URL link)
Thu, April 23, 2015 - 12:00PM to 1:00PM

We no longer need the instructor's name!

We currently have the script to pull out the title (with url), date and time.
All we need to do now is to find a way to extract only workshops from a specific date range (i.e. the coming 2 weeks), does anyone know how we can proceed for this?

**Comment by juanshishido** [comment]
@trinetta,

There are several ways you might want to do this. Look at the structure of the page you're getting the information from. If it's not much data, you can convert the dates to Python datetimes and do something like `if date > cutoff:`.

We can talk more about this.

Remember to push any changes you've made to the master branch (what's on GitHub).

To do so:

```
$ git add <filename>
$ git commit -m '<Message>'
$ git push
```

**Comment by trinetta** [comment]
noted with thanks Juan!

**Comment by juanshishido** [comment]
Merged @tonyshenyy's branch. Closing based on those contributions.
